# Generated by Django 3.1 on 2020-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
