# Generated by Django 3.1 on 2020-08-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_auto_20200819_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertise',
            old_name='sutiable_for_disabled',
            new_name='suitable_for_disabled',
        ),
    ]
