# Generated by Django 3.1 on 2020-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_auto_20200820_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiseimage',
            name='images',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
