# Generated by Django 3.1 on 2020-08-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0005_auto_20200820_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advertiseimage',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
