# Generated by Django 3.1 on 2020-08-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Hata Başlığı')),
                ('content', models.TextField(verbose_name='Hata İçeriği')),
                ('solved', models.TextField(verbose_name='Hata Çözümü')),
                ('software_lang', models.TextField(verbose_name='Kullanılan Diller')),
            ],
        ),
    ]
