# Generated by Django 3.0.8 on 2020-08-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
