# Generated by Django 3.1 on 2020-08-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuenote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='software_lang',
            field=models.TextField(verbose_name='Kullanılan Diller'),
        ),
        migrations.AlterField(
            model_name='note',
            name='solved',
            field=models.TextField(verbose_name='Hata Çözümü'),
        ),
    ]
