"""
Django settings for yerliyabanci project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-5@+y(ylbr($k)445#5kga!jijl55as=a#u_m!45k(fo_m2w!v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webpack_loader',
    'vuenote',
    'user',
    'rest_framework',
    'django.contrib.sites',
    'allauth.account',
    'allauth',
    'allauth.socialaccount',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_auth.registration',
    'advirtise'



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'yerliyabanci.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yerliyabanci.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'tr'



TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_DIRS = [
    os.path.join(BASE_DIR, "static")
]

WEBPACK_LOADER = {

    'DEFAULT' : {

            'CACHE' : not DEBUG,
            'BUNDLE_DIR_NAME': '',
            'STATS_FILE' : os.path.join(BASE_DIR,'frontend/webpack-stats.json'),
            'POLL_INTERVAL' : 0.1,
            'TIMEOUT' : None,
            'IGNORE' : ['.+\.hot-update.js','.+\.map']
    }

}

import time
from datetime import datetime, date, time, timedelta


JWT_AUTH = {
    'JWT_ALLOW_REFRESH': True,
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_EXPIRATION_DELTA':  timedelta(seconds= 5)

}

REST_FRAMEWORK = {

    #'DEFAULT_PERMISSION_CLASSES': [
     #   'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    #],
     #   'DEFAULT_AUTHENTICATION_CLASSES': (
      #  'rest_framework.authentication.TokenAuthentication',
       # 'rest_framework.authentication.SessionAuthentication',
    #)
#   'DEFAULT_PAGINATION_CLASS' : 'rest_framework.pagination.PageNumberPagination',
    #'PAGE_SIZE':6,
#'DEFAULT_PERMISSION_CLASSES' : (
 #       'rest_framework.permissions.IsAuthenticatedOrReadOnly' ,
  #  ),
#'DEFAULT_AUTHENTICATION_CLASSES': (
 #       'rest_framework_jwt.authentication.JSONWebTokenAuthentication' ,
  #      'rest_framework.authentication.SessionAuthentication',
   #     'rest_framework.authentication.BasicAuthentication',
    #),
}


AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]


SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_AUTHENTICATION_METHOD = "username"
AUTH_USER_MODEL = "user.User"
ACCOUNT_FORMS = {'signup' : 'user.forms.CustomSignupForm'}
OLD_PASSWORD_FIELD_ENABLED = False

REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'user.serializer.UserSerializer',
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',

}